add which-blockdev and make prep-kernel use it (fixes /dev/root)
While we are there, some minor cleanups were in order.

Signed-off-by: Matt Sealey <matt@genesi-usa.com>

diff --git a/usr/sbin/prep-kernel b/usr/sbin/prep-kernel
--- a/usr/sbin/prep-kernel
+++ b/usr/sbin/prep-kernel
@@ -3,7 +3,7 @@
 # Copyright (C) 2006  Joey Hess  <joeyh@debian.org>
 # Copyright (C) 2006, 2007, 2008, 2009  Martin Michlmayr <tbm@cyrius.com>
 # Copyright (C) 2009, 2010 Canonical Ltd
-# Copyright (C) 2010, 2011 Genesi USA, Inc. (stripped down for Efika MX)
+# Copyright (C) 2010-2013 Genesi USA, Inc. (stripped down for Efika MX)
 
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
@@ -51,7 +51,13 @@ efikamx_prep_kernel() {
 	bstmp=$tmp.boot.script
 	bsdst=/boot/boot.scr
 	loadaddr=0x90008000
-	rootfs=$(readlink -f /dev/root)
+
+	rootfs=$(which-blockdev)
+
+	if [ "" = "${rootfs}" ]; then
+		echo "Cannot determine root device, exiting.."
+		exit 1
+	fi
 
 	printf "Generating kernel u-boot image... " >&2
 	mkimage -A arm -O linux -T kernel -C none -a ${loadaddr} \
@@ -90,7 +96,7 @@ efikamx_prep_kernel() {
 		eval "sed -i'.bak' -e's,%KERNELVERSION%,$kvers,g' $tmp.boot.script"
 		eval "sed -i'.bak' -e's,%ROOTPARTITION%,$rootfs,g' $tmp.boot.script"
 
-		mkimage -A arm -T script -C none -n "Ubuntu boot script" -d "$tmp.boot.script" \
+		mkimage -A arm -T script -C none -n "Boot Script" -d "$tmp.boot.script" \
 			"${bsdst}" >&2 1>/dev/null
 		echo "done." >&2
 		rm -f "$tmp.boot.script" "$tmp.boot.script.bak"
@@ -132,7 +138,7 @@ if [ ! -e $kfile ]; then
 fi
 
 if [ ! -e $ifile ]; then
-	echo "Warning: Can't find $ifile . Will generate ramdisk less boot." >&2
+	echo "Warning: Can't find $ifile . Will generate ramdisk-less boot." >&2
 fi
 
 # Extract the subarchitecture from the kernel name
